apiVersion: v1
kind: Service
metadata:
  name: aggregatorapi-service
  labels:
    name: aggregatorapi
spec:
  type: LoadBalancer
  ports:
    - port: 4567
      protocol: TCP
      targetPort: 80
  selector:
    app: aggregatorapi-pod
